### ISSUE TITLE
NPM registry publish for 0.2.4?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_core_node#11]
@sunloverz Can you publish 0.2.4? I see it here, but NPM says:
vagrant@Geoffreys-Mac-Pro:/vagrant/node_modules/iron_clad/node_modules/iron_mq_node$ npm install
npm ERR! notarget No compatible version found: iron_core@'>=0.2.4'

**Comment by featalion** [comment]
[Published](https://www.npmjs.com/package/iron_core).
